import { Position, Order } from "./types"

export const MOCK_POSITIONS: Position[] = [
    {
        id: "pos-001",
        userId: "user-1",
        botId: "bot-rocket",
        botName: "Rocket",
        symbol: "BTCUSDT",
        side: "LONG",
        tradeType: "MARGIN",
        marginType: "CROSS",
        leverage: 3,
        entryPrice: 83120.81,
        exitPrice: null,
        currentPrice: 83450.22,
        quantity: 0.14999,
        notionalUsdt: 12467.29,
        realizedPnl: 0,
        unrealizedPnl: 49.41,
        pnlPercent: 0.4,
        fee: 4.98,
        status: "OPEN",
        stopLossOrderId: null,
        takeProfitOrderId: null,
        openedAt: "2026-02-25T13:00:00Z",
        closedAt: null,
    },
    {
        id: "pos-002",
        userId: "user-1",
        botId: "bot-rocket",
        botName: "Rocket",
        symbol: "ETHUSDT",
        side: "LONG",
        tradeType: "MARGIN",
        marginType: "CROSS",
        leverage: 2,
        entryPrice: 3380.5,
        exitPrice: null,
        currentPrice: 3421.55,
        quantity: 2.5,
        notionalUsdt: 8451.25,
        realizedPnl: 0,
        unrealizedPnl: 102.63,
        pnlPercent: 1.21,
        fee: 3.38,
        status: "OPEN",
        stopLossOrderId: "sl-002",
        takeProfitOrderId: "tp-002",
        openedAt: "2026-02-24T09:30:00Z",
        closedAt: null,
    },
    {
        id: "pos-003",
        userId: "user-1",
        botId: "bot-groot",
        botName: "Groot",
        symbol: "SOLUSDT",
        side: "SHORT",
        tradeType: "SPOT",
        marginType: null,
        leverage: 1,
        entryPrice: 182.4,
        exitPrice: null,
        currentPrice: 178.32,
        quantity: 15,
        notionalUsdt: 2736.0,
        realizedPnl: 0,
        unrealizedPnl: 61.2,
        pnlPercent: 2.24,
        fee: 1.09,
        status: "OPEN",
        stopLossOrderId: null,
        takeProfitOrderId: null,
        openedAt: "2026-02-25T16:45:00Z",
        closedAt: null,
    },
    {
        id: "pos-101",
        userId: "user-1",
        botId: "bot-rocket",
        botName: "Rocket",
        symbol: "BTCUSDT",
        side: "SHORT",
        tradeType: "MARGIN",
        marginType: "CROSS",
        leverage: 3,
        entryPrice: 83120.81,
        exitPrice: 83094.095,
        currentPrice: 83094.095,
        quantity: 0.14999,
        notionalUsdt: 12467.29,
        realizedPnl: 4.01,
        unrealizedPnl: 0,
        pnlPercent: 0.03,
        fee: 4.98,
        status: "CLOSED",
        stopLossOrderId: null,
        takeProfitOrderId: null,
        openedAt: "2026-01-31T13:00:00Z",
        closedAt: "2026-01-31T13:30:00Z",
    },
]

export const MOCK_ORDERS: Order[] = [
    {
        id: "ord-001a",
        positionId: "pos-001",
        binanceOrderId: "9691e593-1d8f",
        symbol: "BTCUSDT",
        side: "BUY",
        type: "MARKET",
        purpose: "ENTRY",
        sideEffect: "MARGIN_BUY",
        quantity: 0.14999,
        price: 83120.81,
        stopPrice: null,
        filledQuantity: 0.14999,
        fillPercent: 100,
        avgFillPrice: 83120.81,
        fee: 4.98,
        feeAsset: "USDT",
        status: "FILLED",
        submittedAt: "2026-02-25T13:00:00Z",
        filledAt: "2026-02-25T13:00:00Z",
    },
]
